# 你的管理员面板密码
password=***
# 发送邮件的邮箱地址
notice.mail=177828525@qq.com
mail.username=177828525@qq.com
# 邮箱的smtp的密码
mail.password=***
# 邮箱的smtp服务器地址
mail.host=smtp.qq.com
# 邮箱的smtp端口
mail.port=465
# 不必在意，这个配置
proxy.size=3