// Code generated by gen_logger.go; DO NOT EDIT.

package logger

import "github.com/rs/zerolog"

// Logger 通用日志接口
type Logger interface {
	Debugf(format string, args ...interface{})
	Infof(format string, args ...interface{})
	Warnf(format string, args ...interface{})
	Errorf(format string, args ...interface{})
}

// ZeroLogger zerolog适配器
type ZeroLogger struct {
	Logger zerolog.Logger
}

func (z *ZeroLogger) Debugf(format string, args ...interface{}) {
	z.Logger.Debug().Msgf(format, args...)
}

func (z *ZeroLogger) Infof(format string, args ...interface{}) {
	z.Logger.Info().Msgf(format, args...)
}

func (z *ZeroLogger) Warnf(format string, args ...interface{}) {
	z.Logger.Warn().Msgf(format, args...)
}

func (z *ZeroLogger) Errorf(format string, args ...interface{}) {
	z.Logger.Error().Msgf(format, args...)
}
