name: Auto Build Android AAR

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    # 代码检出（授予写权限）
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    # 配置 Android 环境
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    # 配置 Go 环境
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    # 修复本地脚本环境变量
    - name: Patch Android SDK Path
      working-directory: ./hp-client-golang/android
      run: |
        # 获取 Actions 环境中的 SDK 路径
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        # 修复脚本中的路径指向
        sed -i 's|export ANDROID_HOME=android-21|export ANDROID_HOME=${ANDROID_HOME}|g' build_android_aar.sh
        chmod +x build_android_aar.sh

    # 执行本地编译脚本
    - name: Run Build Script
      working-directory: ./hp-client-golang/android
      run: ./build_android_aar.sh

    # 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hp-client-golang/android
        keep_files: false
        force_orphan: true