name: GoMobile Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 启用提交权限

    - name: Setup Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install NDK 25.1.8937393
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.1.8937393"

    - name: Initialize GoMobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    - name: Build AAR Package
      working-directory: ./hp-client-golang/android  # 进入目标目录
      run: |
        # 检查关键文件是否存在
        if [ ! -f android.go ]; then
          echo "❌ android.go 文件未找到"
          exit 1
        fi
        
        # 执行编译命令
        gomobile bind -target=android -o android.aar -v .
        ls -lh android.aar  # 显示生成文件信息

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hp-client-golang/android  # 指定AAR文件位置
        force_orphan: true  # 强制覆盖历史
        keep_files: false   # 清理旧文件