name: GoMobile Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: "25.1.8937393"  # 必须带引号保证版本号格式
      GO_VERSION: "1.23"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    # 修复NDK安装路径问题
    - name: Install NDK ${{ env.NDK_VERSION }}
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION}}"
        echo "NDK_HOME=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$NDK_HOME" >> $GITHUB_ENV

    # 修复gomobile初始化命令
    - name: Initialize GoMobile
      env:
        ANDROID_NDK_HOME: ${{ env.NDK_HOME }}  # 通过环境变量传递路径
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init

    # 添加环境验证步骤
    - name: Verify Environments
      run: |
        echo "=== 关键路径验证 ==="
        echo "NDK路径: $NDK_HOME"
        ls -l $NDK_HOME/build/core/version.mk  # 验证NDK文件存在
        echo "Go版本: $(go version)"
        echo "Gomobile版本: $(gomobile version)"

    - name: Build AAR
      working-directory: ./hp-client-golang/android
      env:
        ANDROID_NDK_HOME: ${{ env.NDK_HOME }}  # 显式传递NDK路径
      run: |
        gomonile init
        gomobile bind -target=android
        # gomobile bind -target=android -o android.aar -v .

    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hp-client-golang/android
        force_orphan: true
